/**
 * GENERATED by scripts/generate-stage-glyphs.mjs -- do not hand-edit.
 *
 * Flat SVG stand-ins for the six 3D CSS `HomeModel` stages, projected at
 * `StageMini`'s fixed camera so they read as the same buildings. These exist
 * for the places that need *many* stage icons at once -- the Leader
 * hierarchy's count charts and podiums -- where one ~19-node 3D CSS subtree
 * per group is what made the old "Other Connects" board expensive.
 *
 * `StageMini` (the real 3D model) is still the right component anywhere a
 * single, prominent home is shown: Today, Connect, Splash, growth sheet.
 * Editing a stage's geometry in app/styles/home3d.css means re-running the
 * generator, not patching the paths below.
 */
import { memo } from "react";

import type { Stage } from "@/lib/game";

/** Matches StageMini's REFERENCE_DIAMETER, so relative stage sizes agree. */
const VIEWBOX = 300;

/** Progression order, Tent -> Mansion. The one list callers should rank by. */
export const STAGE_ORDER: readonly Stage[] = [
  "Tent",
  "Trailer",
  "Cabin",
  "Apartment",
  "House",
  "Mansion",
];

const SHAPES: Record<Stage, React.ReactNode> = {
  Tent: (
    <>
      <polygon points="25.4,-56.8 91.6,47.4 -40.9,36.4" fill="#b85f4d" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="25.4,-56.8 -40.9,36.4 -91.6,51.3 -25.4,-41.9" fill="#b9604c" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="25.4,-56.8 91.6,47.4 40.9,62.4 -25.4,-41.9" fill="#dc825e" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-25.4,-41.9 40.9,62.4 -91.6,51.3" fill="#d77858" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-26.3,-4.1 -5.1,58.9 -47.5,55.4" fill="#26364a" />
      <polygon points="-26.8,3.9 -11.7,58.5 -41.8,56" fill="#edb55c" />
    </>
  ),
  Trailer: (
    <>
      <polygon points="-66,-53.1 103.5,-39 66,-27.9 -103.5,-42" fill="#b8b59e" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-103.5,-42 66,-27.9 66,53.1 -103.5,39" fill="#ded1ab" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="66,-27.9 103.5,-39 103.5,42 66,53.1" fill="#efe1ba" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-102.7,2.8 63.3,16.7 63.3,29.5 -102.7,15.7" fill="#d16f56" />
      <polygon points="-90.8,-13.8 -50.2,-10.4 -50.2,20.2 -90.8,16.9" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-3.4,-6.5 30.1,-3.7 30.1,26.9 -3.4,24.1" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="35.4,-10.2 65.5,-7.7 65.5,53.6 35.4,51.1" fill="#a8b4ab" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="81,36.8 118.1,39.9 118.1,48.8 81,45.7" fill="#26364a" />
      <circle cx={-66.5} cy={52.5} r={17.5} fill="#26364a" stroke="#d6cdb8" strokeWidth={7} />
      <circle cx={26.2} cy={60.2} r={17.5} fill="#26364a" stroke="#d6cdb8" strokeWidth={7} />
    </>
  ),
  Cabin: (
    <>
      <polygon points="26.8,-114.5 94.7,-55.6 -41.2,-66.9" fill="#704235" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="31.9,-116.1 -36.1,-68.4 -99.9,-49.6 -31.9,-97.3" fill="#354b67" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="31.9,-116.1 99.9,-57.1 36.1,-38.3 -31.9,-97.3" fill="#293b56" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="41.7,-39.9 94.3,-55.4 94.3,51.3 41.7,66.7" fill="#cc7950" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-94.3,-51.3 41.7,-39.9 41.7,66.7 -94.3,55.4" fill="#b96b46" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-26.8,-98.8 41.2,-39.8 -94.7,-51.1" fill="#a75e41" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-94.5,-36.4 41.5,-25.1 41.5,-22.1 -94.5,-33.4" fill="#8b4f38" />
      <polygon points="-94.5,-18.6 41.5,-7.3 41.5,-4.3 -94.5,-15.6" fill="#8b4f38" />
      <polygon points="-94.5,-0.8 41.5,10.5 41.5,13.5 -94.5,2.1" fill="#8b4f38" />
      <polygon points="-94.5,17 41.5,28.3 41.5,31.2 -94.5,19.9" fill="#8b4f38" />
      <polygon points="-94.5,34.7 41.5,46.1 41.5,49 -94.5,37.7" fill="#8b4f38" />
      <polygon points="-94.5,52.5 41.5,63.8 41.5,66.8 -94.5,55.5" fill="#8b4f38" />
      <polygon points="-83.7,-23.4 -59.9,-21.4 -59.9,9.2 -83.7,7.3" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="5.4,-15.9 29.3,-14 29.3,16.7 5.4,14.7" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-42.2,5.8 -12.2,8.3 -12.2,62.6 -42.2,60.1" fill="#e4a94e" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
    </>
  ),
  Apartment: (
    <>
      <polygon points="-37.3,-99.6 88,-89.2 37.3,-74.2 -88,-84.7" fill="#776d84" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="37.3,-74.2 88,-89.2 88,84.7 37.3,99.6" fill="#b4a2bd" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-88,-84.7 37.3,-74.2 37.3,99.6 -88,89.2" fill="#aa98b5" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-88.3,-84.6 -73.3,-83.4 -73.3,90.5 -88.3,89.2" fill="#9485a3" />
      <polygon points="22.1,-75.4 37.1,-74.2 37.1,99.7 22.1,98.4" fill="#887a97" />
      <polygon points="-77,-63.8 -56.7,-62.1 -56.7,-37.4 -77,-39.1" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-36,-60.4 -15.7,-58.7 -15.7,-34 -36,-35.7" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="5.1,-57 25.4,-55.3 25.4,-30.6 5.1,-32.3" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-77,27 -53.2,29 -53.2,59.6 -77,57.7" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="1.6,33.6 25.4,35.6 25.4,66.2 1.6,64.2" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-40.8,38.9 -10.8,41.4 -10.8,95.8 -40.8,93.3" fill="#e4a94e" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-81.7,-44 22.5,-35.4 22.5,-26.5 -81.7,-35.1" fill="#e4d7b9" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-81.7,-5.5 22.5,3.2 22.5,12 -81.7,3.4" fill="#e4d7b9" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-81.7,33 22.5,41.7 22.5,50.6 -81.7,41.9" fill="#e4d7b9" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
    </>
  ),
  House: (
    <>
      <polygon points="29.1,-127.1 112.1,-58.9 -53.9,-72.8" fill="#a57e55" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="34.3,-128.6 -48.7,-74.3 -117.3,-54.1 -34.3,-108.4" fill="#354b67" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="34.3,-128.6 117.3,-60.5 48.7,-40.3 -34.3,-108.4" fill="#293b56" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="54.8,-42.1 111.2,-58.7 111.2,55.9 54.8,72.5" fill="#e1bd80" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-111.2,-55.9 54.8,-42.1 54.8,72.5 -111.2,58.7" fill="#d2ad70" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-29.1,-110 53.9,-41.8 -112.1,-55.6" fill="#d2ad70" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-104.2,3.3 -42.4,8.4 -42.4,64.7 -104.2,59.6" fill="#e5d8b9" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="30.1,-17.1 53.9,-15.2 53.9,15.5 30.1,13.5" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-15,12.7 15,15.2 15,69.5 -15,67" fill="#e4a94e" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-104.6,15.3 -42.8,20.4 -42.8,22.4 -104.6,17.3" fill="#c1aa82" />
      <polygon points="-104.6,29.1 -42.8,34.3 -42.8,36.2 -104.6,31.1" fill="#c1aa82" />
      <polygon points="-104.6,43 -42.8,48.1 -42.8,50.1 -104.6,44.9" fill="#c1aa82" />
      <polygon points="-104.6,56.8 -42.8,61.9 -42.8,63.9 -104.6,58.8" fill="#c1aa82" />
      <polygon points="-13.4,58.7 45.7,63.6 45.7,73.5 -13.4,68.6" fill="#93634d" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
    </>
  ),
  Mansion: (
    <>
      <polygon points="34.7,-148.5 149.5,-79.7 -80,-98.8" fill="#a99b7d" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="39.9,-150 -74.9,-100.3 -154.7,-76.8 -39.9,-126.5" fill="#655d7c" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="39.9,-150 154.7,-81.2 74.9,-57.7 -39.9,-126.5" fill="#766985" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="81,-59.5 148.6,-79.4 148.6,78.6 81,98.5" fill="#eadcaf" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-148.6,-78.6 81,-59.5 81,98.5 -148.6,79.4" fill="#e4d5ad" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-34.7,-128.1 80,-59.2 -149.5,-78.3" fill="#d8c89d" stroke="#172943" strokeWidth={0.6} vectorEffect="non-scaling-stroke" />
      <polygon points="-148.8,-78.5 -111.7,-75.5 -111.7,82.6 -148.8,79.5" fill="#bdac83" />
      <polygon points="43.7,-62.5 80.7,-59.5 80.7,98.6 43.7,95.5" fill="#bdac83" />
      <polygon points="-121.7,-51.5 -96.1,-49.4 -96.1,-20.7 -121.7,-22.9" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-47.1,-45.3 -21.5,-43.2 -21.5,-14.5 -47.1,-16.7" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="27.5,-39.1 53.1,-37 53.1,-8.3 27.5,-10.5" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-123.4,25.4 -96.1,27.7 -96.1,61.2 -123.4,59" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="27.5,37.9 54.9,40.2 54.9,73.8 27.5,71.5" fill="#f6dda0" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-53.7,18.3 -14.8,21.6 -14.8,90.7 -53.7,87.5" fill="#e4a94e" stroke="#26364a" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-104.7,-54.4 27.7,-43.4 27.7,-9.8 -104.7,-20.8" fill="none" stroke="#26364a" strokeWidth={0.9} vectorEffect="non-scaling-stroke" />
      <polygon points="-36.6,-109.7 31.4,-56.7 -104.6,-68" fill="#e4d5ad" stroke="#8c7b64" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-129.4,-19.1 -119.7,-18.3 -119.7,74.5 -129.4,73.7" fill="#fff0c9" stroke="#8c7b64" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-83.5,-15.3 -73.8,-14.5 -73.8,78.3 -83.5,77.5" fill="#fff0c9" stroke="#8c7b64" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-2.3,-8.6 7.4,-7.7 7.4,85.1 -2.3,84.3" fill="#fff0c9" stroke="#8c7b64" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="43.6,-4.7 53.4,-3.9 53.4,88.9 43.6,88.1" fill="#fff0c9" stroke="#8c7b64" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
      <polygon points="-84.1,63.7 2.4,70.9 13,95.5 -94.7,86.6" fill="#d3c298" stroke="#8c7b64" strokeWidth={0.5} vectorEffect="non-scaling-stroke" />
    </>
  ),
};

function StageGlyphBase({
  name,
  size = 24,
  title,
}: {
  name: Stage;
  size?: number;
  title?: string;
}) {
  return (
    <svg
      className="stage-glyph"
      width={size}
      height={size}
      viewBox={`${-VIEWBOX / 2} ${-VIEWBOX / 2} ${VIEWBOX} ${VIEWBOX}`}
      role={title ? "img" : "presentation"}
      aria-hidden={title ? undefined : true}
      aria-label={title}
      focusable="false"
      shapeRendering="geometricPrecision"
    >
      {SHAPES[name]}
    </svg>
  );
}

export const StageGlyph = memo(StageGlyphBase);
